onmetal/gardener-extension-provider-onmetal

- charts/images.yaml
Bump MCM, CSI and CCM image to version v0.1.0.
> Bump MCM, CSI and CCM to v0.1.0

- .github/workflows/publish-docker.yml
- .github/workflows/test.yml
- example/30-controlplane.yaml
- example/30-infrastructure.yaml
- example/30-worker.yaml
Update controlplane, infrastructure and worker examples.
> Update cp, infra and worker examples

- charts/images.yaml
Bump CSI image to `sha-8c59bc6` and MCM image to `sha-1f47d20`
> Bump CSI image to `sha-8c59bc6` and MCM image to `sha-1f47d20`

- charts/images.yaml
Bump CSI driver image to `sha-d332110`.
> Bump CSI driver image to `sha-d332110`

- charts/images.yaml
- MCM v0.48.1
- MCM onmetal v0.1.1
- CSI `sha-a37a71b`
> Bump MCM and CSI

- charts/images.yaml
- charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller.yaml
- charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
Remove NodeIP, DriverName and DriverVersion env vars.
> Remove CSI controller and node driver env vars

- Makefile
Improve Makefile check and goimports directives.
> Improve Makefile check and goimports directives

- charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
- pkg/controller/controlplane/valuesprovider.go
- pkg/onmetal/types.go
Remove unused `csi-resizer` configuration.
> Remove unused `csi-resizer` configuration

- pkg/cmd/options.go
Add missing heartbeat controller to cmd options.
> Add missing heartbeat controller

- charts/images.yaml
Bump CSI image to `v0.1.2` and CCM image to `sha-2153499`.
> Bump CSI image to `v0.1.2` and CCM image to `sha-2153499`

- pkg/apis/onmetal/validation/infrastructure.go
- pkg/apis/onmetal/validation/infrastructure_test.go
- Add validation logic for create and update
- Ensure correct behavior by providing unit tests
Fixes #110
> Add API validation for infrastructure configuration

- charts/images.yaml
> Bump CCM to `v0.1.1`

- pkg/controller/worker/machine_dependencies.go
Deprecate `DeployMachineDependencies` and `CleanupMachineDependencies`.
> Deprecate `DeployMachineDependencies` and `CleanupMachineDependencies`

- .github/workflows/clean.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/test.yml
- go.mod
> Bump golang to 1.20

- charts/images.yaml
- Bump CCM to `v0.1.2`
- Bump CSI to `v0.1.3`
- Bump MCM to `v0.1.2`
> Bump CCM to `v0.1.2`, CSI to `v0.1.3` and MCM to `v0.1.2`

- charts/images.yaml
- Bump MCM to v0.48.2
- Bump `csi-node-driver-registrar` to v2.7.0
- Add CVE categorisation labels to MCM
> Update image vector

- charts/gardener-extension-admission-onmetal/charts/runtime/templates/service.yaml
- charts/gardener-extension-admission-onmetal/values.yaml
- Add topology-aware routing annotations to the service.yaml file
- Disable topology-aware routing in the values.yaml file
> feat: disable topology-aware routing in service deployment

- Makefile
- hack/api-reference/api.json
- hack/api-reference/api.md
- hack/api-reference/config.json
- hack/api-reference/template/members.tpl
- hack/api-reference/template/pkg.tpl
- hack/api-reference/template/tools.go
- hack/api-reference/template/type.tpl
Add API reference doc generation.
> feat: add api reference doc generation

- charts/images.yaml
- Update `machine-controller-manager` tag from `v0.48.2` to `v0.49.2`
- Update `csi-provisioner` tag from `v3.4.0` to `v3.4.1`
> Update `machine-controller-manager` and `csi-provisioner`

- Makefile
- Update `ENVTEST_K8S_VERSION` from `1.26.1` to `1.28.0`
> Update `envtest` to 1.28.0

- pkg/controller/controlplane/valuesprovider.go
Refactor expandable check of `VolumeClasses`
> Refactor expandable check of `VolumeClasses`

- Makefile
- example/20-crd-druid.gardener.cloud_etcds.yaml
- example/20-crd-extensions.gardener.cloud_backupbuckets.yaml
- example/20-crd-extensions.gardener.cloud_backupentries.yaml
- example/20-crd-extensions.gardener.cloud_bastions.yaml
- example/20-crd-extensions.gardener.cloud_clusters.yaml
- example/20-crd-extensions.gardener.cloud_containerruntimes.yaml
- example/20-crd-extensions.gardener.cloud_controlplanes.yaml
- example/20-crd-extensions.gardener.cloud_dnsrecords.yaml
- example/20-crd-extensions.gardener.cloud_extensions.yaml
- example/20-crd-extensions.gardener.cloud_infrastructures.yaml
- example/20-crd-extensions.gardener.cloud_networks.yaml
- example/20-crd-extensions.gardener.cloud_operatingsystemconfigs.yaml
- example/20-crd-extensions.gardener.cloud_workers.yaml
- example/20-crd-resources.gardener.cloud_managedresources.yaml
- hack/generate-crds.sh
- hack/update-codegen.sh
- Update manifest, crd, charts and registration generation
- Update Makefile tools
> Update manifest, crd, charts and registration generation
